package com.entity;

// Generated 2013-8-23 15:06:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Attendanceinfo generated by hbm2java
 */
public class Attendanceinfo implements java.io.Serializable {

    private Integer attendId;
    private Employeeinfo employeeinfo;
    private Date attendTime;
    private int attendState;

    public Attendanceinfo() {
    }

    public Attendanceinfo(Employeeinfo employeeinfo, Date attendTime, int attendState) {
        this.employeeinfo = employeeinfo;
        this.attendTime = attendTime;
        this.attendState = attendState;
    }

    public Integer getAttendId() {
        return this.attendId;
    }

    public void setAttendId(Integer attendId) {
        this.attendId = attendId;
    }

    public Employeeinfo getEmployeeinfo() {
        return this.employeeinfo;
    }

    public void setEmployeeinfo(Employeeinfo employeeinfo) {
        this.employeeinfo = employeeinfo;
    }

    public Date getAttendTime() {
        return this.attendTime;
    }

    public void setAttendTime(Date attendTime) {
        this.attendTime = attendTime;
    }

    public int getAttendState() {
        return this.attendState;
    }

    public void setAttendState(int attendState) {
        this.attendState = attendState;
    }

}
