package com.entity;

// Generated 2013-8-23 15:06:50 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Departmentinfo generated by hbm2java
 */
public class Departmentinfo implements java.io.Serializable {

    private String departId;
    private String departName;
    private Integer departNum;
    private String departDesc;
    private Set employeeinfos = new HashSet(0);

    public Departmentinfo() {
    }

    public Departmentinfo(String departId) {
        this.departId = departId;
    }

    public Departmentinfo(String departId, String departName, Integer departNum, String departDesc, Set employeeinfos) {
        this.departId = departId;
        this.departName = departName;
        this.departNum = departNum;
        this.departDesc = departDesc;
        this.employeeinfos = employeeinfos;
    }

    public String getDepartId() {
        return this.departId;
    }

    public void setDepartId(String departId) {
        this.departId = departId;
    }

    public String getDepartName() {
        return this.departName;
    }

    public void setDepartName(String departName) {
        this.departName = departName;
    }

    public Integer getDepartNum() {
        return this.departNum;
    }

    public void setDepartNum(Integer departNum) {
        this.departNum = departNum;
    }

    public String getDepartDesc() {
        return this.departDesc;
    }

    public void setDepartDesc(String departDesc) {
        this.departDesc = departDesc;
    }

    public Set getEmployeeinfos() {
        return this.employeeinfos;
    }

    public void setEmployeeinfos(Set employeeinfos) {
        this.employeeinfos = employeeinfos;
    }

}
