package com.entity;

// Generated 2013-8-23 15:06:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Extrawork generated by hbm2java
 */
public class Extrawork implements java.io.Serializable {

    private Integer extraId;
    private Employeeinfo employeeinfo;
    private Date workTime;
    private String executes;
    private int workHours;

    public Extrawork() {
    }

    public Extrawork(Employeeinfo employeeinfo, Date workTime, String executes, int workHours) {
        this.employeeinfo = employeeinfo;
        this.workTime = workTime;
        this.executes = executes;
        this.workHours = workHours;
    }

    public Integer getExtraId() {
        return this.extraId;
    }

    public void setExtraId(Integer extraId) {
        this.extraId = extraId;
    }

    public Employeeinfo getEmployeeinfo() {
        return this.employeeinfo;
    }

    public void setEmployeeinfo(Employeeinfo employeeinfo) {
        this.employeeinfo = employeeinfo;
    }

    public Date getWorkTime() {
        return this.workTime;
    }

    public void setWorkTime(Date workTime) {
        this.workTime = workTime;
    }

    public String getExecutes() {
        return this.executes;
    }

    public void setExecutes(String executes) {
        this.executes = executes;
    }

    public int getWorkHours() {
        return this.workHours;
    }

    public void setWorkHours(int workHours) {
        this.workHours = workHours;
    }

}
