package com.entity;

// Generated 2013-8-23 15:06:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Holsinfo generated by hbm2java
 */
public class Holsinfo implements java.io.Serializable {

    private Integer holsId;
    private Employeeinfo employeeinfo;
    private Date applyTime;
    private Date startTime;
    private Date endTime;
    private byte holdays;
    private String executes;
    private int holsState;

    public Holsinfo() {
    }

    public Holsinfo(Employeeinfo employeeinfo, Date applyTime, Date startTime, Date endTime, byte holdays, String executes, int holsState) {
        this.employeeinfo = employeeinfo;
        this.applyTime = applyTime;
        this.startTime = startTime;
        this.endTime = endTime;
        this.holdays = holdays;
        this.executes = executes;
        this.holsState = holsState;
    }

    public Integer getHolsId() {
        return this.holsId;
    }

    public void setHolsId(Integer holsId) {
        this.holsId = holsId;
    }

    public Employeeinfo getEmployeeinfo() {
        return this.employeeinfo;
    }

    public void setEmployeeinfo(Employeeinfo employeeinfo) {
        this.employeeinfo = employeeinfo;
    }

    public Date getApplyTime() {
        return this.applyTime;
    }

    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public byte getHoldays() {
        return this.holdays;
    }

    public void setHoldays(byte holdays) {
        this.holdays = holdays;
    }

    public String getExecutes() {
        return this.executes;
    }

    public void setExecutes(String executes) {
        this.executes = executes;
    }

    public int getHolsState() {
        return holsState;
    }

    public void setHolsState(int holsState) {
        this.holsState = holsState;
    }

}
